title: 'Desarrollo y Mantenimiento de Sistemas Informáticos'
subtitle: 'Itinerario de Sistemas de la Información. Grado en Ingeniería Informática. ULL. Curso 2019/2020'
theme: jekyll-theme-midnight
light: true # midday skin
description: '4º. 1er cuatrimestre. Itinerario de Sistemas de la Información. Grado en Ingeniería Informática. ULL'
exclude:
  - tema1-introduccion/practicas/p3-t1-c3-http/eval
  - tema1-introduccion/practicas/a-public-space-on-the-web-KevMCh
show_downloads: false
future: true
temas: 
  - path: tema0-presentacion
    title: "Tema 0: Presentación"       
  - path: tema1-introduccion
    title: "Tema 1: Introducción"      
  - path: tema2-design
    title: "Tema 2: Análisis y diseño lógico"
  - path: tema3-modelos-emergentes
    title: "Tema 3: Modelos Emergentes"
  - path: tema4-bases-de-datos
    title: "Tema 4: Bases de Datos"
  - path: tema5-mantenimiento
    title: "Tema 5: Mantenimiento y Reingeniería"
  - path: tema6-calidad
    title: "Tema 6: Calidad"

